name: POC on Environments
on:
  push: 
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the test
        run: |
          echo "Hello Test"
  
