name: POC on Environments
on:
  push: 
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      environment:
        description: "Select the Environment:"
        required: true
        type: environment
        options:
        - DEV
        - INT

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run the test
        run: |
          echo "Hello Test"
  
