name: POC on Environments
on:
  push: 
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (INT, UAT)'
        required: true
        default: 'UAT'
        options:
          - INT
          - UAT

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Run the test
        env: 
          TIMEOUT: ${{ vars.TIMEOUT }}
          URL: ${{ vars.URL }}
        run: |
          echo "Hello Test: ${{ inputs.environment }}"
          echo "Key is: ${{ secrets.KEY }}
          echo "Secret is: ${{ secrets.SECRET }}
          echo "TIMEOUT: $TIMEOUT"
          echo "URL: $URL"
  
